# Generated by Django 3.2.25 on 2025-11-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(blank=True, help_text='Temporary placeholder until full CRM integration.', max_length=255)),
                ('audio_file', models.FileField(upload_to='call_recordings/')),
                ('status', models.CharField(choices=[('waiting_transcription', 'Waiting for transcription'), ('transcribed', 'Transcribed'), ('analyzed', 'Analyzed')], default='waiting_transcription', max_length=32)),
                ('transcript', models.TextField(blank=True)),
                ('golden_nuggets', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
