# Generated by Django 3.2.25 on 2026-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='transcript_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcription_job_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='deal_title',
            field=models.CharField(blank=True, help_text='Enter deal name', max_length=255),
        ),
    ]
