# Generated by Django 3.2.25 on 2026-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20260209_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('he', 'Hebrew'), ('en', 'English')], default='auto', max_length=8),
        ),
    ]
