# Generated by Django 3.2.25 on 2026-02-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_callrecording_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='followup_text',
            field=models.TextField(blank=True),
        ),
    ]
