# Generated by Django 3.2.25 on 2026-02-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20260219_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='followup_text',
        ),
    ]
