# Generated by Django 3.2.25 on 2026-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_remove_callrecording_followup_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='analysis_text',
        ),
        migrations.RemoveField(
            model_name='callrecording',
            name='feedback_text',
        ),
        migrations.AddField(
            model_name='callrecording',
            name='analysis_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='feedback_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
