# Generated by Django 3.2.25 on 2026-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_notificationdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
