# Generated by Django 3.2.25 on 2026-03-29 18:01

from django.db import migrations, models


def dedup_notification_deliveries(apps, schema_editor):
    """
    For each (recording_id, kind) group, keep the row with the highest id
    and delete the rest. Runs before the unique_together constraint is applied.
    """
    NotificationDelivery = apps.get_model("conversations", "NotificationDelivery")
    seen = {}
    # Order by id ascending so we process oldest first; last one seen per pair wins.
    for delivery in NotificationDelivery.objects.order_by("id"):
        key = (delivery.recording_id, delivery.kind)
        if key in seen:
            NotificationDelivery.objects.filter(id=seen[key]).delete()
        seen[key] = delivery.id


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_alter_notificationdelivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.RunPython(dedup_notification_deliveries, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('recording', 'kind')},
        ),
    ]
