# Generated by Django 3.2.25 on 2026-03-31 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_org'),
        ('conversations', '0011_notificationdelivery_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_recordings', to='accounts.organization'),
        ),
    ]
